name: mdi-workshop
channels:
  - conda-forge
  - nodefaults
dependencies:
# python packages
  - python==3.11
  - pip
  - pandas
  - numpy
  - ipykernel
  - statsmodels
  - matplotlib
# R packages
# pip installs
  # - pip:
